export const EXPERIENCE = [
  {
    title: "Senior Software Engineer",
    company: "ThirstyFish",
    period: "Sept, 2024 - Present",
    description: [
      "Developed core features for 4Rooms, a multi-tenant property management system, including modules for property management, room reservations, Channex integration, restaurant management, HRMS, shift management, and supply chain",
      "Built the 4Rooms booking engine with Stripe integration, decoupling a Next.js and Tailwind CSS frontend from a headless Laravel CMS with PostgreSQL for optimized performance and scalability",
      "Implemented location-based domain routing and dynamic, region-specific content delivery, including catalogs, blogs, and job postings, for ABS Group using Laravel",
      "Delivered custom Laravel applications including an event ticketing system with Stripe and Xero integrations for Legends Between Wickets, a mock-test booking platform for Arch Education, and a time-slot-based food pre-ordering app for BiryaniBowl",
      "Mentored junior engineers through code reviews and pair programming, while coordinating end-to-end releases across frontend and backend teams",
    ],
    technologies: [
      "Laravel",
      "Core PHP",
      "React.js",
      "Next.js",
      "React Bootstrap",
      "Tailwind CSS",
      "MySQL",
      "PostgreSQL",
      "Stripe",
    ],
  },
  {
    title: "Full-Stack Developer",
    company: "Image Media World",
    period: "Oct, 2023 - Aug, 2024",
    description: [
      "Worked across Laravel, MySQL, Spring Boot, Node.js, and PostgreSQL backends with Next.js and Blade on the frontend",
      "Developed backend features for Phroses, an internal HRMS platform built on Spring Boot, with a Next.js and Tailwind CSS frontend",
      "Led a custom Node.js web application, improving performance and long-term maintainability",
      "Built an e-commerce platform in Laravel with Stripe integration",
    ],
    technologies: [
      "Next.js",
      "Spring Boot",
      "Node.js",
      "Laravel",
      "PostgreSQL",
      "MySQL",
      "Tailwind CSS",
      "Blade",
    ],
  },
  {
    title: "Backend Developer",
    company: "ZedexInfo Pvt Ltd",
    period: "Dec, 2022 - Sept, 2023",
    description: [
      "Responsible for backend development using Laravel and MySQL, with additional frontend contributions in Next.js, Tailwind CSS, and Blade",
      "Built organization management features, improved resource search and filtering for ResourceQueue, and integrated the Zoom API to support in-platform interview scheduling",
      "Developed a job portal and candidate application flow for Mechanics Hub, including Indeed API integration",
    ],
    technologies: [
      "Laravel",
      "MySQL",
      "Next.js",
      "Tailwind CSS",
      "Blade",
      "Zoom API",
    ],
  },
];
